name: Deploy to Dev
on:
  push:
    branches: [dev]
jobs:
  build-and-deploy:
    uses: semicolon-devteam/actions-template/.github/workflows/ci-next-docker.yml@main
    with:
      environment: dev
      registry: docker.io
    secrets: inherit
